### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [IBM/ruby-sdk-core#5]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by mamoonraja** [comment]
We don't have `sudo: false` in our Travis config.

**Comment by cclauss** [comment]
You have a __sudo:__tag which is now completely deprecated in Travis because the __sudo__tag is _always_available and there is no way to turn it off.

**Comment by mamoonraja** [comment]
My bad, I got confused by the wording.
